title: Nordic MathML Guidelines
description: Guidelines for Mathematical Content in HTML Files, Using MathML
author: Nordic Agencies
email: 
url: "https://nlbdev.github.io/mathml-guidelines"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - archive/
  - scripts/

# Include files
include:
  - _pages
  - images

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"