name: Quick Build Check
on: [push]
jobs:
  quick_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: latest.tex
          continue_on_error: false
      - name: Build status
        run: |
          if [ -f "./src/latest.pdf" ]; then
            echo "✅ LaTeX compilation successful"
          else
            echo "❌ LaTeX compilation failed"
            exit 1
          fi
