name: Pull Request Validation
on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: latest.tex
          continue_on_error: false
      
      - name: Check for LaTeX compilation errors
        run: |
          if [ ! -f "./src/latest.pdf" ]; then
            echo "❌ LaTeX compilation failed - PDF not generated"
            exit 1
          else
            echo "✅ LaTeX compilation successful"
          fi
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-build
          path: ./src/latest.pdf
        if: always()